### ISSUE TITLE
Ejercicios de consola

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-confident-students#2]
[Ejercicios_de_hilos_.aplicacion.de.consola.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-confident-students/files/15120053/Ejercicios_de_hilos_.aplicacion.de.consola.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
